### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by mojavelinux** [opendevise/bespoke-highlight#4]
Release v1.0.0 of the plugin. This is the initial release.

**Comment by mojavelinux** [comment]
Here's the procedure I've been following to release:

## Release
- populate readme field in package.json with flattened package-README.md contents (first time only or after change to README)
- remove `-dev` suffix from version number in package.json
- set revnumber and revdate in revision line of README.adoc document header (e.g., `v1.0.0, 2016-07-12`)
- bump release-version attribute in README.adoc (format: vX.Y.Z)
- run `gulp`
- commit as `git commit . -m "Release x.y.z"`
- tag using `git tag -a vX.Y.Z -m X.Y.Z`
- push using `git push origin master --tags`
- publish using `npm publish`
- deploy demo using `gulp deploy` (if relevant)

## Post-release
- bump version and add `-dev` suffix in package.json
- remove revision line from README.adoc
- run `gulp`
- commit as `git commit . -m "Begin development on next release [skip ci]"`
- push using `git push origin master`

**Comment by hsablonniere** [comment]
At which point do you merge on master?
Do you merge on your machine or with the PR?

**Comment by mojavelinux** [comment]
Lately, I've been using the squash and commit on GitHub (because I'm kind of lazy like that). If the pull request got messed up, as they sometimes do when coming from contributors still learning the ropes, then I might do it on my own machine with some fix up commits.

**Comment by mojavelinux** [comment]
When I do a squash merge on GitHub, I add "PR" in front of the pull request number so it's clear that it is a reference to a pull request and not an issue. You can see examples in the jekyll-asciidoc log. https://github.com/asciidoctor/jekyll-asciidoc/commits/master

**Comment by hsablonniere** [comment]
I prefer a merge commit. It helps in the history to understand what happened and it creates "bluckles" in the history graph.

We'll discuss the `Begin development on next release [skip ci]`. I'm not used to that.

**Comment by hsablonniere** [comment]
I did not do the Post-release yet but release 1.0.0 is published !!

**Comment by mojavelinux** [comment]
> I prefer a merge commit. It helps in the history to understand what happened...

That's totally fine. I should have mentioned that when the PR contains more than one commit, then using a merge commit (or a rebase without squash) is more ideal because it preserves all the individual changes. I think the answer is really "it depends" :)

**Comment by mojavelinux** [comment]
> We'll discuss the Begin development on next release [skip ci]. I'm not used to that.

How else do you set the version to `.dev`? I don't think it's a good idea to keep the version at the release version because as the repository moves forward, it misleads people into thinking it's still the same. And the only way to change the version is to make a new commit. Do you have an alternative approach?

**Comment by mojavelinux** [comment]
Congratulations on the release!

I think we still need to setup Travis, right. I'll enable from the Travis side.

**Comment by hsablonniere** [comment]
> I think we still need to setup Travis, right. I'll enable from the Travis side.

OK, perfect.

> I don't think it's a good idea to keep the version at the release version because as the repository moves forward, it misleads people into thinking it's still the same.

I've never missed this "JAVA *-SNAPSHOT" thing in the JS community. Most of the big projects I know of increment version in package.json when they release. In the meantime, **master** has a package.json with the _"previous"_ version but it's not really a problem. I'm not confused by that because I have git tags to find the version I want in the source and I have NPM to find the version of the module I need.

Here's a few repos that work like this, package.json version is at the latest version and there has been commits since :
- angular 2 : [package.json](https://github.com/angular/angular/blob/master/package.json) / [commits since last tag](https://github.com/angular/angular/compare/2.0.0-rc.4...master)
- eslint : [package.json](https://github.com/eslint/eslint/blob/master/package.json) / [commits since last tag](https://github.com/eslint/eslint/compare/v3.0.1...master)
- redux : [package.json](https://github.com/reactjs/redux/blob/master/package.json) / [commits since last tag](https://github.com/reactjs/redux/compare/v3.5.2...master)

Angular 1.x seems to do something exotic in their [package.json](https://github.com/angular/angular.js/blob/master/package.json).

I'm open to discussions but we need something clear (documented) and automated.

**Comment by mojavelinux** [comment]
I feel pretty strongly about this issue. I really don't like the idea of master claiming to be a version that it isn't. I'd be okay with bumping the version forward without adding a development suffix, but I definitely don't think it should remain on the previous version. On this issue, I think many other projects get it wrong and we're the ones who are leading the way.

JQuery is at least one other project that uses a development suffix. In their case, they use `-pre`. See https://github.com/jquery/jquery/blob/master/package.json

**Comment by hsablonniere** [comment]
OK. I'm not a great fan but as you know, I like to challenge my opinions 😏 so I did a few readings on semver and looked how jQuery does it. I think I'm OK to try their method.

Here's an example of how they do it with the 3.0.0 release. From this commit : https://github.com/jquery/jquery/commit/7d21f02b9ec9f655583e898350badf89165ed4d5 which has a package.json with [version 3.0.0-pre](https://github.com/jquery/jquery/blob/7d21f02b9ec9f655583e898350badf89165ed4d5/package.json#L5) :
- They create a child commit https://github.com/jquery/jquery/commit/c25cd3c4ba60daf166dfcee729f0bc69fd52a565 with a package.json with version `3.0.0`
  - They tag it and push the tag.
  - This commit is NOT in the history of master.
- They create a child commit https://github.com/jquery/jquery/commit/019c8f1f41de8696b2b90c43648fe339efdb6a02 with a package.json with version `3.0.1-pre`
  - They push the commit into master.
  - This commit is in the history of master.

This prevents this kind of back and forth in the history of the package.json : `3.0.0-pre => 3.0.0 => 3.0.1-pre`. It creates this kind of commit graph :

![capture du 2016-07-14 15-02-32](https://cloud.githubusercontent.com/assets/236342/16840274/046490e2-49d4-11e6-95d0-2e7f18e729dc.png)

Having master with `2.1.2-pre` does not mean we are to release 2.1.2. For example, at some point, they decided to move [to `3.0.0-pre`](https://github.com/jquery/jquery/commit/7a607c5673fa36f9818f19e349871600a2938b1e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) in nov 2014 and they only released `3.0.0` in jun 2016.

I found a lib by mgol (who works on jQuery) to automate this a bit : https://www.npmjs.com/package/npm-bump.

WDYT?

**Comment by mojavelinux** [comment]
I'd be okay with the commit that only appears in the tag and having master leapfrog over it. That actually fits really well with a fully-automated release because there would be no manual steps to perform (and possibly mess up).

> Having master with 2.1.2-pre does not mean we are to release 2.1.2.

Absolutely correct. It only means that at the time we had planned for that, but plans change. The version should always represent the next _intended_ release. It helps people see where we are headed.

**Comment by mojavelinux** [comment]
> I found a lib by mgol (who works on jQuery) to automate this a bit https://www.npmjs.com/package/npm-bump.

Honestly, I'd be fine with custom code, or our own module. But if something already does exactly what we want, then by all means we should use it.

**Comment by mojavelinux** [comment]
Btw, I think this issue should be closed. Correct?

We should also setup milestones and tags for this repo. I'd like to automate that in the future when we create a new repository. Otherwise, we keep having to come around to it.

**Comment by mojavelinux** [comment]
I tagged the release issue as infrastructure. If you have a better tag choice, I'm open to it.

**Comment by hsablonniere** [comment]
I tried [npm-bump](https://www.npmjs.com/package/npm-bump) and it creates two commits in the hsitory which is not like jQuery and I'm not a great fan of having 2 commits on each release.

I also tried [np](https://github.com/sindresorhus/np). It does NPM publishing, test and other stuffs but it does not do the "jQuery 2 commits" stuff.

I also reviewed (without testing) a few others and it's not very promising.

My proposition : create a custom module for all our projects (inspired by npm-bump and np). It would handle everything we need :
- run tests, build...
- version bump package.json, README...
- tag
- commit (as defined in this discussion)
- NPM publish
- gh-pages deploy

**Comment by mojavelinux** [comment]
> My proposition : create a custom module for all our projects (inspired by npm-bump and np). It would handle everything we need :

I would be very much in support of that option. I think we'll end up saving time in the end and getting exactly the control we need. We'll just need a good name, but we can tap Sarah and Lisa for ideas there.

**Comment by hsablonniere** [comment]
Status :
- :smile: [v1.0.0](https://github.com/opendevise/bespoke-prism/releases/tag/1.0.0) was tagged properly on github
- :cry: during automation of the release process, a bad 1.0.0 version was publish to NPM which can't be removed
- :trollface: Therefore, I released a [1.0.1](https://github.com/opendevise/bespoke-prism/releases/tag/1.0.1)
  - I took the opportunity to shrink the size of the NPM package with https://github.com/opendevise/bespoke-prism/commit/11ad84f920126eb9b2d0b286d21a77b6f103851b
  - We'll have to investigate if we should move all the `dependencies` to `devDependencies` since they're already packaged in the dist release (see #7).

**Comment by hsablonniere** [comment]
The automation of our release process can be followed here : https://github.com/opendevise/opendevise-release-bot/issues

**Comment by mojavelinux** [comment]
> during automation of the release process, a bad 1.0.0 version was publish to NPM which can't be removed

Happens to the best of us.

> I took the opportunity to shrink the size of the NPM packag

I always wonder whether to include all files are just the essentials. I suppose we should follow this pattern for all our plugins.

> We'll have to investigate if we should move all the dependencies to devDependencies 

I'll follow-up in that issue.

**Comment by mojavelinux** [comment]
:+1:
