### ISSUE TITLE
Support alternative highlighter libraries (i.e., act as a meta package)

### ISSUE THREAD

**Issue by mojavelinux** [opendevise/bespoke-highlight#6]
I'm concerned that by naming the plugin bespoke-highlight, we shut out plugins that use an alternative to Prism such as highlight.js. We need to think about how we will allow an alternative highlighter such as highlight.js to be used.

To achieve that, I think we should convert this package to a meta package that does one of two things:
1. Delegates to an implementation-specific package such as bespoke-prism
2. Introduces an option to select which highlighter to use

While it's good that the user doesn't have to worry about choosing a highlighter, I don't think the plugin should be hardwired to Prism.

**Comment by mojavelinux** [comment]
I think option 2 is going to be difficult to support when using browser globals. It will work when using CommonJS modules because we can use dynamic requires.

Option 1 would be a static pointer that we can change over time. But what's important is that someone can just pick the implementation-specific package to control which highlighter is used (e.g., bespoke-prism, bespoke-highlightjs). In other words, bespoke-highlight would just be an alias for whichever highlighter is our recommended default.

**Comment by hsablonniere** [comment]
I agree about the naming confusion.

As of right now, I would let things as is and maybe go for option 1 if needed. In the meantime, we could add that the choice of PrismJS is opinionated.

**Comment by hsablonniere** [comment]
Actually, I'm not a great fan of option 1 (or option 2). I think the generator should help to make the choice the day we'll have many options. Having a meta package that just do delegation feels a bit convoluted.

Maybe we need to rename it to `bespoke-highlight-prism` right now.

**Comment by mojavelinux** [comment]
> Maybe we need to rename it to bespoke-highlight-prism right now.

I would be open to that. However, I still don't think we need to word "highlight" in the name. Prism is a proper name, so it already communicates what it's about. That's why I suggest simply `bespoke-prism`. We might then have the package `bespoke-hljs` to provide integration with highlight.js (as hljs seems to be the accepted short name for highlight.js). Thus:
- bespoke-prism
- bespoke-hljs
- bespoke-highlight (an alias of bespoke-prism or bespoke-hljs)

I'll note that bespoke-math currently using katex. That's another example of an opinionated package. That plugin probably should have been released as bespoke-katex. However, a case could be made for an alias package that does math without revealing which implementation it is. That's why I still like the idea of also having bespoke-highlight just pick an implementation. Perhaps we can release this alias package out of one of the repositories.

**Comment by mojavelinux** [comment]
Having said all that, if you feel strongly about this combination:
- bespoke-highlight-prism (but name the function `prism()`)
- bespoke-highlight-hljs (but name the function `hljs()`)
- bespoke-highlight (an alias of bespoke-highlight-prism or bespoke-highlight-hljs)

then I could get behind that.

**Comment by hsablonniere** [comment]
> However, a case could be made for an alias package that does math without revealing which implementation it is. That's why I still like the idea of also having bespoke-highlight just pick an implementation. Perhaps we can release this alias package out of one of the repositories.

I don't like the idea of having a meta package that just does delegates highlighting to the one we feel is the best. My proposition :
1. Rename this module to `bespoke-prism`
2. Wait for some user to create or ask for `bespoke-hljs`
   - If both options are used, we can evolve the generator so it asks which one the user wants
3. We don't create any alias plugin. It adds tests for us and code in the browserified bundle of the user. The generator can still strongly suggest one of the highlighters.

**Comment by hsablonniere** [comment]
Package is renamed!
